# application.template.yaml

# === Profile Activation ===
spring:
  config:
    activate:
      on-profile: profile-name

  # === Application Metadata ===
  application:
    name: your-application-name

  # === Database Configuration ===
  datasource:
    # URL to your MySQL database inside Docker network
    url: jdbc:mysql://localhost:3306/your_database_name?serverTimezone=${database.timezone:Asia/Ho_Chi_Minh}&createDatabaseIfNotExist=true
    username: your_db_username
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # === JPA & Hibernate ===
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # === File Upload Configuration ===
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

# === Server Configuration ===
server:
  port: ${server.port:8080}
  servlet:
    context-path: /api/your-project-name

# === JWT Configuration ===
jwt:
  secret: your_base64_encoded_secret_at_least_512_bits
  expiration: 86400000
  refresh-expiration: 604800000
  issuer: LMS

# === Swagger/OpenAPI Configuration ===
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-docs
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  show-actuator: true

# === Actuator Configuration ===
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,beans
  endpoint:
    health:
      show-details: always

# === Logging Configuration ===
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.yourcompany.yourproject: DEBUG